"""add_section_remove_unique

Revision ID: 7c36eb680a50
Revises: f38787824b50
Create Date: 2026-01-30 18:04:43.633692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c36eb680a50'
down_revision: Union[str, None] = 'f38787824b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('section', sa.String(), nullable=True))
    op.drop_index('ix_courses_course_code', table_name='courses')
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.create_index('ix_courses_course_code', 'courses', ['course_code'], unique=True)
    op.drop_column('courses', 'section')
    # ### end Alembic commands ###
