"""add face embedding table

Revision ID: 8f948355ed82
Revises: f7c87557053d
Create Date: 2026-02-16 16:26:41.338595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f948355ed82'
down_revision: Union[str, None] = 'f7c87557053d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('class_sessions_course_id_fkey', 'class_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'class_sessions', 'courses', ['course_id'], ['id'])
    op.drop_constraint('enrollments_student_id_fkey', 'enrollments', type_='foreignkey')
    op.drop_constraint('enrollments_course_id_fkey', 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key('enrollments_course_id_fkey', 'enrollments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('enrollments_student_id_fkey', 'enrollments', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.create_foreign_key('class_sessions_course_id_fkey', 'class_sessions', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
