"""add_schedule_columns_fixed

Revision ID: f38787824b50
Revises: 221545747180
Create Date: 2026-01-30 17:43:41.877329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f38787824b50'
down_revision: Union[str, None] = '221545747180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('day_of_week', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('end_time', sa.String(), nullable=True))
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('enrollments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('face_embeddings', sa.Column('model_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'face_embeddings', ['user_id'])
    op.drop_column('face_embeddings', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_embeddings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'face_embeddings', type_='unique')
    op.drop_column('face_embeddings', 'model_name')
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('enrollments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('courses', 'end_time')
    op.drop_column('courses', 'start_time')
    op.drop_column('courses', 'day_of_week')
    # ### end Alembic commands ###
