"""add model_name column

Revision ID: f6f419e6d703
Revises: 221545747180
Create Date: 2026-01-29 14:56:22.819438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'f6f419e6d703'
down_revision: Union[str, None] = '221545747180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('enrollments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('face_embeddings', sa.Column('model_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'face_embeddings', ['user_id'])
    op.drop_column('face_embeddings', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_embeddings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'face_embeddings', type_='unique')
    op.alter_column('face_embeddings', 'embedding_vector',
               existing_type=sa.JSON(),
               type_=pgvector.sqlalchemy.Vector(dim=512),
               existing_nullable=False)
    op.drop_column('face_embeddings', 'model_name')
    op.alter_column('enrollments', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('enrollments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
